# Generated by Django 5.1.2 on 2024-11-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_collection_options_alter_customer_options_and_more'),
        ('store', '0005_auto_20210625_1631'),
    ]

    operations = [
    ]
